### PR TITLE
Update package

### PR DESCRIPTION
**Pull request by jrappen**
This is a major PR. See the `Unreleased` section of the `CHANGELOG.md` for details.

@randy3k If you have questions, just ask.

---

You'll need to:

* decide which version tag you want next
  * put info in `.github/ISSUE_TEMPLATE.md`
  * put info in `CHANGELOG.md`
  * tag the last commit (and release on Github)

### CODE REVIEW

**Comment by jrappen** [comment]
@randy3k

I forgot a few lines in `./src/__init__.py`, sorry about that. You still interested in this? I'd redo this with the missing lines.

**Comment by randy3k** [comment]
Thank for the work, I will need some time to review the changes.

**Comment by jrappen** [comment]
Should I make a `./docs` folder for Github Pages and prepare English and German docs there based upon [QingWei-Li/docsify](https://github.com/QingWei-Li/docsify)?

**Comment by jrappen** [comment]
@randy3k done

**Comment by jrappen** [comment]
@randy3k I have addressed your desired changes in randy3k/ProjectManager@e485110. Was there anything else you would like me to change?

**Comment by randy3k** [comment]
@jrappen I have added you as a collaborator in case you want to contribute further to this package.

By the way, thanks for the amazing work.

**Comment by jrappen** [comment]
@randy3k Thanks, I'll pass on this one.

On another note, FYI PayPal has this site `paypal.me/{user}` or `paypal.me/{user}/{amount-in-your-currency}`. Currently there's no support for recurring donations, the interface is slightly more pleasing, though.

**Pull request merged**
