### PR TITLE
feat: add ability to use custom active project indicator

### PR DESCRIPTION
**Pull request by acheronfail**
This PR adds the ability to add a custom indicator to the select project list.

### CODE REVIEW

**Comment by randy3k** [comment]
looks good. thank you.

BTW, what symbol do you use?

**Comment by acheronfail** [comment]
Wow! That was merged in record time! 🎉 

> BTW, what symbol do you use?

I prefer to use `•`.

**Comment by acheronfail** [comment]
I was wondering as well, would you be open to another PR which lets the user choose if the indicator is placed at the beginning rather than this end of the Project name?

**Comment by randy3k** [comment]
a possible solution is

```python
DISPLAY="{project_name} {active_project_indicator}"
DISPLAY.format(project_name=project_name, active_project_indicator= active_project_indicator)
```
and let user to change DISPLAY.

**Comment by acheronfail** [comment]
That's even better 👍 I'll make a PR for it.

**Pull request merged**
