### PR TITLE
added edit_current action

### PR DESCRIPTION
**Pull request by budRich**
this action will open the currently active projects `sublime-project` file instead of the command palette.

### CODE REVIEW

**Comment by randy3k** [comment]
Thx for the PR. However, i don’t think i would merge it. There is already a “Edit Project” command in Command Palette.

**Comment by budRich** [comment]
yeah. I just saw that, (and removed my fork from my own package list in favor for yours, also cleaned up the Command list to not have duplicate entries'. I think i have used both the built in one and yours, without not knowing. Thank you for this package, it' s one of the best, and makes a big difference (in my workflow, by simplifying and sobering the project functionality) while still not introducing any bloat, great work. I am making a little sublime series on my youtube, i will make one episode about projects, and will feature your thing.

**Comment by randy3k** [comment]
Thank you for the kind words. Post me a link when you have it and I'll put it in README.

**Comment by tukusejssirs** [comment]
I think this PR should be closed.

**Pull request closed without merging**
